export const skills = [
  { value: "JavaScript", count: 1, color: "bg-green-500" },
  { value: "React", count: 2, color: "bg-yellow-500" },
  { value: "Nodejs", count: 3, color: "bg-red-500" },
  { value: "Express.js", count: 4, color: "bg-pink-500" },
  { value: "HTML5", count: 5, color: "bg-slate-500" },
  { value: "MongoDB", count: 6, color: "bg-sky-500" },
  { value: "CSS3", count: 7, color: "bg-violet-500" },
  { value: "SQL", count: 8, color: "bg-amber-500" },
  { value: "React", count: 9, color: "bg-emerald-500" },
  { value: "Redux", count: 10, color: "bg-cyan-500" },
  { value: "Material UI", count: 1, color: "bg-blue-500" },
  { value: "Haedless UI", count: 2, color: "bg-purple-500" },
  { value: "REST API", count: 3, color: "bg-fuchsia-500" },
  { value: "SCSS", count: 4, color: "bg-rose-500" },
  { value: "TypeScript", count: 5, color: "bg-indigo-500" },
  { value: "React Hook Form", count: 6, color: "bg-violet-800" },
  { value: "React Testing Libraries", count: 7, color: "bg-red-300" },
  { value: "Jest", count: 8, color: "bg-blue-800" },
  { value: "MobX", count: 9, color: "bg-amber-800" },
  { value: "ReduxToolKit", count: 1, color: "bg-cyan-800" },
];
